### PR TITLE
[#18] Fix bare statements matching

### LINKED ISSUE #18: Base statements should be partial matches

### PR DESCRIPTION
**Pull request by gbp**
Fixes #18 
Connect to https://github.com/mysociety/verification-pages/issues/500

### CODE REVIEW

File: spec/membership_comparison_spec.rb [hunk 1]
```diff
@@ -40,6 +40,24 @@
     specify { expect(comparison.problems).to be_empty }
   end
 
+  context 'single existing P39, bare statements' do
```
Comment (tmtmtmtm) [inline spec/membership_comparison_spec.rb]: this claims there's only a single existing P39, but the `existing` below shows two entries…
